version: "2.2"
services:
  vscode:
    image: caretdev/code-server
    ports:
      - 8080:8080
    volumes:
      - ./src:/opt/intersystems
  iris:
    hostname: iris
    image: containers.intersystems.com/intersystems/iris-community:2021.2.0.649.0
    volumes:
      - ./src:/opt/intersystems
    ports:
     - 52773:52773
     - 1972:1972